name: talker
description: Advanced and simple error handler and logger for dart and flutter apps with history, sharing, customization, etc.
version: 2.4.2
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  talker_logger: #^2.2.1
    # path:
    #   ../talker_logger
    git:
      url: https://github.com/cselti/talker-2.x
      ref: main
      path: packages/talker_logger/

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.1
