name: talker_shop_app_example
description: Talker flutter example shop application
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  talker_flutter:
    path:
      ../../packages/talker_flutter
  talker_dio_logger: 
    path:
      ../../packages/talker_dio_logger
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^5.0.0
  url_launcher: ^6.1.7
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
