name: talker_flutter
description: Flutter extensions for talker. Advanced and simple error handler and logger for dart and flutter apps with history, sharing, customization, etc.
version: 2.4.4
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  talker: #^2.4.0
    # path:
    #   ../../packages/talker
    git:
      url: https://github.com/cselti/talker-2.x
      ref: main
      path: packages/talker/
  talker_dio_logger: #^1.3.0
    # path:
    #   ../../packages/talker_dio_logger
    git:
      url: https://github.com/cselti/talker-2.x
      ref: main
      path: packages/talker_dio_logger/
  group_button: ^5.2.2
  path_provider: ^2.0.13
  share_plus: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
